version: '3'

services:
  base:
    build: .
    pull_policy: never
    image: samu/server

  server:
    pull_policy: never
    image: samu/server
    command: ["python3", "server.py"]
    stop_signal: SIGINT
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - logs:/var/log
    networks:
      - net
    depends_on:
      - base
    restart: always

  post:
    pull_policy: never
    image: samu/server
    command: ["python3", "post_service.py", "-s"]
    stop_signal: SIGINT
    volumes:
      - .:/usr/src/app
      - logs:/var/log
    networks:
      - net
    depends_on:
      - server
      - base
    restart: always

networks:
  net:

volumes:
  logs: