version: '3'

services:
  base:
    build: .
    pull_policy: never
    image: samu/server

  server:
    pull_policy: never
    image: samu/server
    command: ["sh", "/usr/src/app/server.sh", ">>", "/var/log/server.log"]
    stop_signal: SIGINT
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - logs:/var/log
    networks:
      - net
    depends_on:
      - base
    restart: always

  post:
    pull_policy: never
    image: samu/server:0.1
    command: ["sh", "/usr/src/app/post_service.sh", "-s", ">>", "/var/log/post_service.log"]
    stop_signal: SIGINT
    volumes:
      - .:/usr/src/app
      - logs:/var/log
    networks:
      - net
    depends_on:
      - server
      - base
    restart: always

networks:
  net:

volumes:
  logs: